spring:
  jpa:
    database: mysql
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: til_blog
    url: jdbc:mysql://localhost:3306/til_blog?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
logging:
  level:
    me:
      park:
        tildiaryspringboot: DEBUG
    org:
      hibernate: info

jwt:
  header: Authorization
  secret: UGFya1N1bmdId2FuLXRpbC1kaWFyeS1zcHJpbmdib290UGFya1N1bmdId2FuLXRpbC1kaWFyeS1zcHJpbmdib290UGFya1N1bmdId2FuLXRpbC1kaWFyeS1zcHJpbmdib290Cg==
  token-validity-in-seconds: '86400'